export const dummyPatientData = [
  {
    firstName: "Roger",
    surname: "Smith",
    title: "Mr",
    address: "122 Street Road Birmingham",
    pregnant: false,
    dob: "1988-02-01",
    gender: "Male",
    gpSurgery: "Happy Health",
    nhsNumber: 123456789,
    phoneNumber: "01213457854",
    postcode: "B91 7QY",
    email: "rsmith123@email.com",
    prepaid: "2022-09-01",
  },
  {
    firstName: "Victoria",
    surname: "Smith",
    title: "Mrs",
    address: "122 Street Road Birmingham",
    pregnant: false,
    dob: "1988-06-01",
    gender: "Female",
    gpSurgery: "Happy Health",
    nhsNumber: 164928174,
    phoneNumber: "01213457854",
    postcode: "B91 7QY",
    email: "vickismith@email.com",
    prepaid: "2022-09-01",
  },
  {
    firstName: "Katie",
    surname: "Lefoe",
    title: "Miss",
    address: "1 Close Birmingham",
    pregnant: true,
    dob: "1990-05-02",
    gender: "Female",
    gpSurgery: "Happy Health",
    nhsNumber: 892758490,
    phoneNumber: "01216783217",
    postcode: "B21 9UI",
    email: "katielefoe@email.com",
    prepaid: "2022-07-01",
  },
];

export const dummyPrescriptionData = [
  {
    patient_id: 1,
    name: "simvastatin",
    reason: "lower cholesterol",
    total: 14,
    frequency: "twice a day",
    dosage: 2,
    date: "2022-08-04",
    active: true,
    measurement: "mg",
    monitoring: true,
    monitoringSchedule: 4,
    override: "Need to lose weight",
    quantity: 300,
    status: "paused",
  },
  {
    patient_id: 1,
    name: "apixaban",
    reason: "prevent blood clots",
    total: 14,
    frequency: "twice a day",
    dosage: 2,
    date: "2022-08-04",
    active: true,
    measurement: "mg",
    monitoring: true,
    monitoringSchedule: 4,
    override: "Patient has clotting issue",
    quantity: 100,
    status: "in use",
  },
];
